apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: haproxy-server
  name: haproxy-server
spec:
  replicas: 1
  selector:
    matchLabels:
      run: haproxy-server
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: haproxy-server
    spec:
      containers:
      - image: gcr.io/google-samples/hello-app:1.0
        name: hello-server
        ports:
        - containerPort: 8080
        resources: {}
      - image: haproxy:latest
        name: haproxy-server
        ports:
        - containerPort: 8000
          name: http
        - containerPort: 26999
          name: stats
        volumeMounts:
        - mountPath: /usr/local/etc/haproxy/haproxy.cfg
          name: haproxy-cfgmap
          subPath: haproxy.cfg
        readinessProbe:
          initialDelaySeconds: 15
          periodSeconds: 5
          timeoutSeconds: 1
          successThreshold: 2
          failureThreshold: 2
          tcpSocket:
            port: 26999
        resources: {}
      - image: quay.io/prometheus/haproxy-exporter:v0.9.0
        name: haproxy-exporter
        command:
        - /bin/haproxy_exporter
        - --haproxy.scrape-uri=http://localhost:26999/haproxy?stats;csv
        ports:
        - containerPort: 9101
          name: http
        resources: {}
      - image: gcr.io/google-containers/prometheus-to-sd:v0.2.1
        name: prometheus-to-sd
        ports:
          - name: profiler
            containerPort: 6060
        command:
          - /monitor
          - --stackdriver-prefix=custom.googleapis.com
          - --source=kube-state-metrics:http://localhost:9101/metrics
          - --pod-id=$(POD_NAME)
          - --namespace-id=$(POD_NAMESPACE)
      volumes:
      - name: haproxy-cfgmap
        configMap:
          name: haproxy-cfgmap
status: {}